[install]
is_configured = true
build = 1

[package]
id = process_mining

[ui]
is_visible = true
label = Process Mining

[launcher]
author = joehanse
description = Process mining directed graph visualization from raw event sequences
version = 1.0.0
