[process_mining]
label = Process Mining
description = Process mining directed graph from event sequences
default_height = 600
allow_user_selection = true
disabled = 0
search_fragment = | table _time case_id activity status resource
