[porsche_cursor_battery]
filename = porsche_battery.csv

[porsche_cursor_range]
filename = porsche_range.csv

[porsche_cursor_charging]
filename = porsche_charging.csv

[porsche_cursor_sensors]
filename = porsche_sensors.csv

[porsche_cursor_energy]
filename = porsche_energy.csv

[porsche_cursor_regen]
filename = porsche_regen.csv
