# Battery Gauge
display.visualizations.custom.porsche_cursor.battery_gauge.field = <string>
display.visualizations.custom.porsche_cursor.battery_gauge.labelField = <string>
display.visualizations.custom.porsche_cursor.battery_gauge.title = <string>
display.visualizations.custom.porsche_cursor.battery_gauge.unit = <string>
display.visualizations.custom.porsche_cursor.battery_gauge.maxValue = <string>
display.visualizations.custom.porsche_cursor.battery_gauge.minValue = <string>
display.visualizations.custom.porsche_cursor.battery_gauge.valueFontSize = <string>
display.visualizations.custom.porsche_cursor.battery_gauge.labelFontSize = <string>
display.visualizations.custom.porsche_cursor.battery_gauge.accentIntensity = <string>
display.visualizations.custom.porsche_cursor.battery_gauge.goodColor = <string>
display.visualizations.custom.porsche_cursor.battery_gauge.warnColor = <string>
display.visualizations.custom.porsche_cursor.battery_gauge.dangerColor = <string>
display.visualizations.custom.porsche_cursor.battery_gauge.goodThreshold = <string>
display.visualizations.custom.porsche_cursor.battery_gauge.warnThreshold = <string>

# Range KPI
display.visualizations.custom.porsche_cursor.range_kpi.field = <string>
display.visualizations.custom.porsche_cursor.range_kpi.labelField = <string>
display.visualizations.custom.porsche_cursor.range_kpi.deltaField = <string>
display.visualizations.custom.porsche_cursor.range_kpi.unitField = <string>
display.visualizations.custom.porsche_cursor.range_kpi.sparklineField = <string>
display.visualizations.custom.porsche_cursor.range_kpi.title = <string>
display.visualizations.custom.porsche_cursor.range_kpi.valueFontSize = <string>
display.visualizations.custom.porsche_cursor.range_kpi.labelFontSize = <string>
display.visualizations.custom.porsche_cursor.range_kpi.accentIntensity = <string>
display.visualizations.custom.porsche_cursor.range_kpi.valueColor = <string>
display.visualizations.custom.porsche_cursor.range_kpi.accentColor = <string>

# Charge Gauge
display.visualizations.custom.porsche_cursor.charge_gauge.field = <string>
display.visualizations.custom.porsche_cursor.charge_gauge.labelField = <string>
display.visualizations.custom.porsche_cursor.charge_gauge.targetField = <string>
display.visualizations.custom.porsche_cursor.charge_gauge.title = <string>
display.visualizations.custom.porsche_cursor.charge_gauge.unit = <string>
display.visualizations.custom.porsche_cursor.charge_gauge.maxValue = <string>
display.visualizations.custom.porsche_cursor.charge_gauge.minValue = <string>
display.visualizations.custom.porsche_cursor.charge_gauge.valueFontSize = <string>
display.visualizations.custom.porsche_cursor.charge_gauge.labelFontSize = <string>
display.visualizations.custom.porsche_cursor.charge_gauge.accentIntensity = <string>
display.visualizations.custom.porsche_cursor.charge_gauge.arcColor = <string>
display.visualizations.custom.porsche_cursor.charge_gauge.targetColor = <string>

# Sensor Table
display.visualizations.custom.porsche_cursor.sensor_table.sensorField = <string>
display.visualizations.custom.porsche_cursor.sensor_table.tempField = <string>
display.visualizations.custom.porsche_cursor.sensor_table.statusField = <string>
display.visualizations.custom.porsche_cursor.sensor_table.trendField = <string>
display.visualizations.custom.porsche_cursor.sensor_table.title = <string>
display.visualizations.custom.porsche_cursor.sensor_table.headerFontSize = <string>
display.visualizations.custom.porsche_cursor.sensor_table.bodyFontSize = <string>
display.visualizations.custom.porsche_cursor.sensor_table.accentIntensity = <string>
display.visualizations.custom.porsche_cursor.sensor_table.normalColor = <string>
display.visualizations.custom.porsche_cursor.sensor_table.warningColor = <string>
display.visualizations.custom.porsche_cursor.sensor_table.criticalColor = <string>

# Energy Area
display.visualizations.custom.porsche_cursor.energy_area.valueField = <string>
display.visualizations.custom.porsche_cursor.energy_area.timeField = <string>
display.visualizations.custom.porsche_cursor.energy_area.title = <string>
display.visualizations.custom.porsche_cursor.energy_area.unit = <string>
display.visualizations.custom.porsche_cursor.energy_area.valueFontSize = <string>
display.visualizations.custom.porsche_cursor.energy_area.labelFontSize = <string>
display.visualizations.custom.porsche_cursor.energy_area.accentIntensity = <string>
display.visualizations.custom.porsche_cursor.energy_area.fillColor = <string>
display.visualizations.custom.porsche_cursor.energy_area.lineColor = <string>
display.visualizations.custom.porsche_cursor.energy_area.gridDivisions = <string>

# Regen Donut
display.visualizations.custom.porsche_cursor.regen_donut.categoryField = <string>
display.visualizations.custom.porsche_cursor.regen_donut.valueField = <string>
display.visualizations.custom.porsche_cursor.regen_donut.title = <string>
display.visualizations.custom.porsche_cursor.regen_donut.valueFontSize = <string>
display.visualizations.custom.porsche_cursor.regen_donut.labelFontSize = <string>
display.visualizations.custom.porsche_cursor.regen_donut.accentIntensity = <string>
display.visualizations.custom.porsche_cursor.regen_donut.colors = <string>
