[install]
is_configured = 0
build = 1

[id]
name = redbull_viz
version = 1.0.0

[package]
id = redbull_viz
check_for_updates = false

[ui]
is_visible = true
label = Red Bull Racing Telemetry

[launcher]
author = Custom Viz
description = Red Bull Racing F1 telemetry visualizations
version = 1.0.0
