[install]
is_configured = 0
build = 1

[id]
name = hm_viz

[package]
id = hm_viz
check_for_updates = false

[ui]
is_visible = true
label = H&M Global Sales

[launcher]
author = Splunk Viz Team
description = Themed custom visualizations for H&M global sales dashboards
version = 1.0.0
