[hm_viz_kpi_summary]
filename = hm_kpi_summary.csv

[hm_viz_regional_sales]
filename = hm_regional_sales.csv

[hm_viz_channel_split]
filename = hm_channel_split.csv

[hm_viz_revenue_trend]
filename = hm_revenue_trend.csv

[hm_viz_market_status]
filename = hm_market_status.csv
