[nike_training_club_kpis]
filename = nike_training_club_kpis.csv

[nike_training_club_programs]
filename = nike_training_club_programs.csv

[nike_training_club_trends]
filename = nike_training_club_trends.csv

[nike_training_club_trainers]
filename = nike_training_club_trainers.csv

[nike_training_club_cities]
filename = nike_training_club_cities.csv

[nike_training_club_activity]
filename = nike_training_club_activity.csv
