[install]
is_configured = 0
build = 1

[id]
name = netflix_viz

[package]
id = netflix_viz
check_for_updates = false

[ui]
is_visible = true
label = Netflix Visualizations

[launcher]
author = Splunk Viz Pack
description = Netflix themed streaming KPI visualizations with Stranger Things aesthetic
version = 1.0.0
