[install]
is_configured = 0
build = 1

[id]
name = hbo_max_viz

[package]
id = hbo_max_viz
check_for_updates = false

[ui]
is_visible = true
label = HBO Max Viz Pack

[launcher]
author = Joe Hansen
description = Premium HBO Max themed custom visualizations for Splunk Dashboard Studio
version = 1.0.0
