[Nike Gauge - Engagement]
search = | inputlookup nike_gauge_demo.csv | head 1
dispatch.earliest_time = -24h
dispatch.latest_time = now
display.general.type = visualizations
display.visualizations.type = custom
display.visualizations.custom.type = nike_gauge.engagement_gauge
display.visualizations.custom.nike_gauge.engagement_gauge.valueField = value
display.visualizations.custom.nike_gauge.engagement_gauge.targetField = target
display.visualizations.custom.nike_gauge.engagement_gauge.labelField = label
display.visualizations.custom.nike_gauge.engagement_gauge.accentColor = #CDFF00
display.visualizations.custom.nike_gauge.engagement_gauge.showTarget = true
display.visualizations.custom.nike_gauge.engagement_gauge.accentIntensity = 70
