[install]
is_configured = 0
build = 1

[id]
name = disney_plus_viz
version = 1.0.0

[package]
id = disney_plus_viz
check_for_updates = false

[ui]
is_visible = true
label = Disney+ Visualizations

[launcher]
author = Custom Viz
description = Disney+ themed custom visualizations for Dashboard Studio
version = 1.0.0
